name: ManagementGroups

on:
  push:
    branches:
      - "ManagementGroups"

env:
  location: 'eastus'
  rootMg: 'Luke-Root'

jobs:
  AzureBicepDeploy:
    name: 'AzureBicepDeploy'
    runs-on: ubuntu-latest
 
    steps:
    -  name: Checkout Code
       uses: actions/checkout@v2

    -  name: Build Management Group 
       run: |
         az bicep build --file AzureCloud/Root-MG/Root-MG-Test.bicep

    -  name: Azure Login
       uses: azure/login@v1
       with:
         creds: ${{ secrets.MSDN_SECRET }}

    -  name: Deploy Management Group template
       uses: azure/CLI@v1
       with:
         inlineScript: |
           az account show
           az deployment tenant create -f AzureCloud/Root-MG/Root-MG-Test.json -l ${{ env.location }}